version: "3.9"

services:
  api:
    build:
      context: ./api
    container_name: WOC-1_api
    ports:
      - "5050:5000"
    volumes:
      - ./api:/app
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: WOC-1_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
